# -*- coding: utf-8 -*-
"""prak 6 algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwSkroYS2X_TQZnWpnBKpcb9iTxn_Yst
"""

skor = 0
nilaimurid = list()
ulang = 0
nomor = 0

while ulang == 0:
    nomor += 1
    x = str(input('"selesai" untuk mengakhiri!\nmasukan nilai : '))

    if x == 'selesai':
        ulang = 1

    else:

        if x == 'A':
            skor = float(4.00)

        elif x == 'A-':
            skor = float(3.75)

        elif x == 'B+':
            skor = float(3.50)

        elif x == 'B':
            skor = float(3.00)

        elif x == 'B-':
            skor = float(2.75)

        elif x == 'C+':
            skor = float(2.50)

        elif x == 'C':
            skor = float(2.00)

        elif x == 'C-':
            skor = float(1.75)

        elif x == 'D':
            skor = float(1.50)

        elif x == 'E':
            skor = float(1.25)

        else:
            print('Saya tidak mengerti...')
            skor = 0
        print(('\nNilai ke-{0} = {1}').format(nomor,skor))
        nilaimurid.append(skor)

rata2 = sum(nilaimurid) / len(nilaimurid)
print('rata rata nilai murid tersebut:', rata2)

hitung = 0
jawab = "ya"

while(jawab == "ya"):
    inputbulan = int(input("masukan bulan nya: "))
    inputtahun = int(input("masukan tahun nya: "))
    jawab = str(input("ingin lanjut atau tidak: "))

    def hitung_bulan():
        if(inputbulan >= 13 or inputbulan <= 0):
            print("bulan tidak terdaftar di dalam kalender")

        elif(inputbulan == 1 or inputbulan == 3 or inputbulan == 5 or inputbulan == 7 or inputbulan == 8 or inputbulan == 10 or inputbulan == 12):
            print("Ini termasuk 31 hari")

        elif inputbulan == 2:
            if(inputtahun % 4 == 0 and (inputtahun % 100 != 0 or inputtahun % 400 == 0)):
                print("Ini 29 hari")
            else:
                print("Ini merupakan 28 hari")

        else:
            print("Ini merupakan 30 hari")

    hitung_bulan()